Revert "feat: merge changes from devel"

diff --git a/files/system/usr/bin/cherry b/files/system/usr/bin/cherry
--- a/files/system/usr/bin/cherry
+++ b/files/system/usr/bin/cherry
@@ -2,10 +2,8 @@
 
 CONTAINER_CONFIG_DIR="/etc/containerconf"
 USER_CONTAINER_CONFIG_DIR="$CONTAINER_CONFIG_DIR/$USER"
-CONTAINER_LIST_FILE="$CONTAINER_CONFIG_DIR/configs.d/.cherry/list.txt"
+CONTAINER_LIST_FILE="$CONTAINER_CONFIG_DIR/configs.d/list.txt"
 CONTAINER_OVERRIDE_CONFIG="$HOME/.config/containerconf.d/override.conf"
-FILENAME_TMP=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 35 ; echo '')
-PS3="> "
 
 help() {
   cat <<EOF 
@@ -14,7 +12,7 @@ Usage: cherry <subcommand> [option]
 Subcommands:
   stem                        baseOS commands
   branch                      containerOS commands
-  pesticide                   FSguard commands
+  bootc                       wrapper for bootc
   version                     show program version
   help                        show this dialogue
 EOF
@@ -25,103 +23,45 @@ os-help() {
 Usage: cherry stem [option]
 
 Options:
-  roots                       run a command on the host system
-  grow                        upgrade the host system and related utils
-  status                      show the status of the host system
+  exec                        run a command on the host
+  shell                       open a shell ont he host (/bin/sh)
   help                        show this dialogue
 EOF
 }
 
-container-help() {
+contaienr-help() {
   cat <<EOF
 Usage: cherry branch [option]
 
 Options:
-  grow                        create a new container
-  snap                        remove an existing container
-  jump <container_name>       switch to a different container
-  help                        show this dialogue
-EOF
-}
-
-pesticide-help() {
-  cat <<EOF
-Usage: cherry pesticide [option]
-
-Options:
-  status                      show the status of enrolled directories
-  check                       check the integrity of enrolled directories
-  apply                       enroll a new directory
+  new                         create a new container
+  rm                          remove an existing container
+  switch                      switch to a different container
   help                        show this dialogue
 EOF
 }
 
 version() {
-  echo "cherry v2.0.0"
+  echo "cherry v1.2.3-beta"
 }
 
-status() {
-  cat <<EOF
-bourbonOS $(cat /etc/bourbonOS-version)
-pesticide: $(/usr/libexec/pesticide/status) $(/usr/libexec/pesticide/version)
-=======================
-host: $(hostname)
-kargs: $(cat /proc/cmdline)
-kernver: $(uname -r)
-=======================
-current container: $(cat "$CONTAINER_OVERRIDE_CONFIG")
-containers:
-$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
-=======================
-ostree status:
-$(bootc status)
-EOF
-}
+new() {
+  read -p "Do you want to (1) choose from a list of images, or (2) specify your own (advanced)? 1/2: " container_new_choice
 
-new_container() {
-  echo "Do you want to:"
-  select container_new_choice in "Choose from a list of images" "Specify your own (advanced)"; do
-    case $REPLY in
-      1|2) break ;;
-      *) echo "Invalid choice. Please select 1 or 2." ;;
-    esac
-  done
   case "$container_new_choice" in
     1)
-      echo "Select an image from the list:"
-      select image in $(cat "$CONTAINER_LIST_FILE"); do
-        if [[ -n "$image" ]]; then
-          distrobox-assemble create --file /etc/containerconf/configs.d/$image.ini
-          echo "Done! You can switch to the container using 'cherry branch switch'."
-          break
-        else
-          echo "Invalid selection."
-          exit 1
-        fi
-      done
+      echo "Choose a container to create:"
+      cat "$CONTAINER_LIST_FILE"
+      read -p "> " container_new_choice_config
+      distrobox-assemble create --file "${container_new_choice_config}.ini"
+      echo "Container created."
       ;;
     2)
-      read -p "Container URL/alias: " manual_container_url
+      read -p "Container URL: " manual_container_url
       read -p "Container name: " manual_container_name
-      echo "An editor will open to allow you to specify additional options."
-      echo "If you do not know how to specify additional options in the editor,"
-      echo "Please type the word help and press enter."
-      echo "When you're done looking at the help file, press q to exit."
-      echo "Then, reselect 'Specify your own (advanced)' to continue."
-      echo "If you don't need help, just press enter."
-      read -p container_help_var "> "
-      if [[ "$container_help_var" == "help" ]]; then
-        less /etc/containerconf/configs.d/.cherry/editor-syntax.txt
-        new_container
-      else
-        cp /etc/containerconf/configs.d/.ini-template /tmp/$FILENAME_TMP.ini
-        sed -i "s/<name>/$manual_container_name/g" /tmp/$FILENAME_TMP.ini
-        sed -i "s/<url>/$manual_container_url/g" /tmp/$FILENAME_TMP.ini
-        nano /tmp/$FILENAME_TMP.ini
-        distrobox-assemble create --file /tmp/$FILENAME_TMP.ini
-        rm /tmp/$FILENAME_TMP.ini
-      fi
-      echo "Done! You can switch to the container using 'cherry branch switch'."
+      read -p "Extra flags to pass to 'distrobox-create'. Optional. > " manual_container_flags
+      distrobox-create --pull --image "$manual_container_url" --name "branch-$manual_container_name" $manual_container_flags
+      echo "Container created!"
       ;;
     *)
       echo "Invalid choice."
@@ -130,116 +70,88 @@ new_container() {
   esac
 }
 
-remove_container() {
-  if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
-    echo "No containers to remove."
-    exit 1
+rm() {
+  read -p "Are you sure you want to do this? y/n: " rm_confirm
+  if [[ "$rm_confirm" == "y" ]]; then
+    echo "Input the container to remove."
+    echo "Containers:"
+    distrobox-list
+    read -p "> " container_name_rm
+    if [[ "$container_name_rm" == "cherry-cli" ]]; then echo "You cannot delete the default container!" && exit 1; fi
+    distrobox-rm "$container_name_rm"
   else
-    echo "Select a container by its number to remove it."
-    select container in $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$'); do
-      if [[ -n "$container" ]]; then
-        distrobox-rm $container
-        break
-      else
-        echo "Invalid selection."
-        exit 1
-      fi
-    done
+    echo "Cancelling."
+    exit 1
   fi
 }
 
-switch_container() {
-  if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
-    echo "No containers to switch to."
-    exit 1
-  else
-    echo "Select a container by its number to switch to it."
-    select container in $(distrobox-list | awk '{print $3}' | grep -v '^NAME$' | sed 's/^cherry-cli$/default container/'); do
-      if [[ -n "$container" ]]; then
-        exec distrobox-enter $container -- bash
-      else
-        echo "Invalid selection."
-        exit 1
-      fi
-    done
-  fi
+switch() {
+  echo "Input the container to switch to."
+  echo "Containers:"
+  distrobox-list
+  read -p "> " container_name_switch
+  echo "$container_name_switch" > "$CONTAINER_OVERRIDE_CONFIG"
+  echo "Switch complete. Reopen this terminal to open your new container."
+  echo "Note that it may take a second for the container to start."
 }
 
-os_exec() {
+os-exec() {
   "$@"
 }
 
-os_upgrade() {
+os-shell() {
   clear
-  topgrade
+  echo "You are running a shell on the HOST SYSTEM! Proceed with caution."
+  /bin/sh
+}
+
+container-menu() {
+  case "$1" in
+    new)
+      new
+      ;;
+    rm)
+      shift
+      rm "$@"
+      ;;
+    switch)
+      switch
+      ;;
+    *)
+      help
+      exit 1
+      ;;
+  esac
+}
+
+os-menu() {
+  case "$1" in
+    exec)
+      shift
+      os-exec
+      ;;
+    shell)
+      os-shell
+      ;;
+    *)
+      help
+      exit 1
+      ;;
+  esac
 }
 
 case "$1" in
   stem)
     shift
-    case "$1" in
-      roots)
-        shift
-        os_exec "$@"
-        ;;
-      grow)
-        os_upgrade
-        ;;
-      status)
-        status
-        ;;
-      help)
-        os-help
-        ;;
-      *)
-        os-help
-        exit 1
-        ;;
-    esac
+    os-menu "$@"
     ;;
   branch)
     shift
-    case "$1" in
-      grow)
-        new_container
-        ;;
-      snap)
-        shift
-        remove_container "$@"
-        ;;
-      jump)
-        switch_container
-        ;;
-      help)
-        container-help
-        ;;
-      *)
-        container-help
-        exit 1
-        ;;
-    esac
+    container-menu "$@"
     ;;
-  pesticide)
+  bootc)
     shift
-    case "$1" in
-      status)
-        /usr/libexec/pesticide/status
-        ;;
-      check)
-        /usr/libexec/pesticide/check
-        ;;
-      apply)
-        shift
-        /usr/libexec/pesticide/enroll "$@"
-        ;;
-      help)
-        pesticide-help
-        ;;
-      *)
-        pesticide-help
-        exit 1
-        ;;
-    esac
+    bootc "$@"
     ;;
   version)
     version
